### PR TITLE
Server in Swift :D

### PR DESCRIPTION
**Pull request by kittinunf**
screen shot 2016-06-27 at 7 17 37 pm

Use `carthage update --platform mac` to build server project.

### CODE REVIEW

**Comment by kittinunf** [comment]
Shall we merge this?

**Comment by macbaszii** [comment]
@kittinunf I made my branch `feature/items` from your branch not master, can we wait for that first ?

**Comment by kittinunf** [comment]
OK!

**Comment by macbaszii** [comment]
@kittinunf 👍 let's do it!

**Pull request merged**
